name: risk-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - stumpy
  - pip
  - pip:
    - pyod==0.7.9
    - d6tflow==0.1.9